### ISSUE TITLE
invalid device function

### ISSUE THREAD

**Issue by GYTuuT** [svip-lab/impersonator#48]
When i run demo_imitator.py, it always comes the error:**invalid device function**  like this:

Error in forward_face_index_map_2: invalid device function
Error in forward_face_index_map_1: invalid device function
Error in forward_face_index_map_2: invalid device function
Error in forward_face_index_map_1: invalid device function
Error in forward_face_index_map_2: invalid device function
Error in forward_face_index_map_1: invalid device function

and the results of other two demos are the same.
my GPUs are 2080ti and the environments is python-3.7, torch-1.3.1, CUDA-10.0, and does the version of my packages cause the error?

**Comment by GYTuuT** [comment]
I have solved my problem by replacing a value with a smaller one. 
The value I changed is in line 22 of _thirdparty/neural_renderer/neural_renderer/cuda/rasterize_cuda_kernel.cu_
And then run setup.py.

**Comment by ThereIsNoWindBag** [comment]
What was the cause?

**Comment by piaozhx** [comment]
It is caused by new version of pytorch (1.2 and later), a simple solution is down-grade  pytorch to 1.0 or 1.1 and re-complie neural-render

**Comment by GYTuuT** [comment]
> What was the cause?

use pure python rather than conda when creat virtual environments, install the requirments.txt  and complie neural_render,  than it worked. I don't know if it works for you.

**Comment by piaozhx** [comment]
@GYTuuT @ThereIsNoWindBag  I guess you have more than one type gpu (e.g. rtx2080ti and gtx 1080ti) and complie neural render from one type and run on another bacause new version pytorch has stricter compatibility . if you use one type gpu to complie and run or just use pytorch 1.1, it will work well.

**Comment by ThereIsNoWindBag** [comment]
I followed your advice and it works. Thanks a lot!

**Comment by samarthKabbur** [comment]
> > What was the cause?
> 
> use pure python rather than conda when creat virtual environments, install the requirments.txt and complie neural_render, than it worked. I don't know if it works for you.

How can I do this @GYTuuT ?
